---
- name: Template PostgreSQL config
  ansible.builtin.template:
    owner: root
    src: postgresql/postgresql.conf
    dest: "{{ postgresql.prefix.config }}/ansible.conf"
    mode: "0644"
  notify: Restart PostgreSQL

- name: Include the custom PostgreSQL file
  ansible.builtin.lineinfile:
    create: yes
    owner: root
    mode: "0644"
    path: "{{ postgresql.prefix.config }}/postgresql.conf"
    line: "include_if_exists = 'ansible.conf'"
