- name: Template PostgreSQL config
  loop:
    - "{{ postgresql.prefix.config }}/main/conf.d/ansible.conf"
  template:
    src: postgresql/postgresql.conf
    dest: "{{ item }}"
  notify: Restart PostgreSQL
