---
- name: Create databases
  postgresql_db:
    login_user: root
    maintenance_db: root
    name: "{{ item.name }}"
    owner: "{{ owner }}"
    encoding: "{{ encoding }}"
    lc_collate: "{{ lc_collate }}"
    lc_ctype: "{{ lc_ctype }}"
    template: "{{ template }}"
  loop_control:
    label: "{{ item.name }} owner={{ owner }} encoding={{ encoding }} lc_collate={{ lc_collate }} lc_ctype={{ lc_ctype }} template={{ template }}"
  vars:
    owner: "{{ none if item.owner|default(none) == none else (postgresql.users[item.owner[1:]].username if item.owner.startswith('~') else item.owner) }}"
    encoding: "{{ item.encoding|default(postgresql.database_defaults.encoding, true) }}"
    lc_collate: "{{ item.lc_collate|default(postgresql.database_defaults.lc_collate, true) }}"
    lc_ctype: "{{ item.lc_ctype|default(postgresql.database_defaults.lc_ctype, true) }}"
    template: "{{ item.template|default(postgresql.database_defaults.template, true) }}"
  with_items: "{{ postgresql.databases.values()|list }}"
