---
- name: Configure data directory
  lineinfile: path="{{ item.path }}" regexp="{{ item.regexp }}" line="{{ item.line }}"
  loop_control:
    label: "{{ item.path }} {{ item.line }}"
  with_items:
    - path: /etc/rc.conf
      regexp: "^postgresql_data="
      line: 'postgresql_data="{{ postgresql.data_dir }}"'

- name: Create data directroy
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ postgresql.user }}"
    group: "{{ postgresql.user }}"
  with_items:
    - "{{ postgresql.data_dir }}"
  register: data_dir

- name: Initialize data directory
  command: "{{ postgresql.init_command }}"
  with_items:
    - "{{ postgresql.data_dir }}"
  when: data_dir.changed

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started

- name: Create root superuser
  postgresql_user:
    login_user: "{{ postgresql.user }}"
    db: postgres
    name: root
    role_attr_flags: SUPERUSER

- name: Create root database
  postgresql_db:
    login_user: "{{ postgresql.user }}"
    maintenance_db: postgres
    name: root
    owner: root
    encoding: "{{ postgresql.database_defaults.encoding }}"
    lc_collate: "{{ postgresql.database_defaults.lc_collate }}"
    lc_ctype: "{{ postgresql.database_defaults.lc_ctype }}"
    template: "{{ postgresql.database_defaults.template }}"
