---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - python3-debian
      - gpg
      - gpg-agent
    update_cache: yes

- name: Remove the legacy apt repository
  ansible.builtin.file:
    dest: /etc/apt/sources.list.d/postgresql.list
    state: absent


- name: Add the PostgreSQL apt repository
  register: postgresql_add_apt_repository
  ansible.builtin.deb822_repository:
    name: postgresql
    uris: "{{ postgresql.repository.apt.repository }}"
    signed_by: "{{ postgresql.repository.apt.key_url }}"
    types: [deb]
    components: [main]
    suites: "{{ postgresql.repository.apt.suites }}"
    state: present
    enabled: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: postgresql_add_apt_repository.changed

- name: Ensure data dir is mounted before PostgreSQL is started
  community.general.ini_file:
    path: "/etc/systemd/system/postgresql.service.d/UnitRequiresMountsFor.conf"
    create: yes
    section: Unit
    option: RequiresMountsFor
    value: /var/lib/postgresql
    mode: "0644"
    owner: "root"

- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - "{{ postgresql.repository.apt.package }}"
      - python3-psycopg2
      - acl

- name: Generate PostgreSQL locales
  loop: "{{ postgresql.databases | dict2items }}"
  register: postgresql_locales_generated
  community.general.locale_gen:
    name:
      - "{{ item.value.lc_collate | default(postgresql.database_defaults.lc_collate, true) }}"
      - "{{ item.value.lc_ctype | default(postgresql.database_defaults.lc_ctype, true) }}"

- name: Restart PostgreSQL
  when: postgresql_locales_generated.changed
  ansible.builtin.service:
    name: postgresql
    state: restarted
