---
- name: Get PostgreSQL version
  changed_when: no
  register: postgresql_version_full
  check_mode: no
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      psql --version | sed "s/^.*\([0-9][0-9]\).*$/\1/"

- name: Set PostgreSQL version fact
  ansible.builtin.set_fact:
    postgresql_version: "{{ postgresql_version_full.stdout }}"

- name: Set PostgreSQL version fact
  ansible.builtin.set_fact:
    postgresql: "{{ postgresql | combine({'version': postgresql_version_full.stdout}) }}"
