---
- name: Enable service
  lineinfile: path="{{ item.path }}" regexp="{{ item.regexp }}" line="{{ item.line }}"
  loop_control:
    label: "{{ item.path }}"
  with_items:
    - path: /etc/rc.conf
      regexp: "^postgresql_enable="
      line: 'postgresql_enable="YES"'

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
