- name: Create root user
  when: ansible_system == 'Linux'
  become_user: postgres
  postgresql_user:
    login_user: postgres
    db: postgres
    name: root
    role_attr_flags: SUPERUSER

- name: Create users
  postgresql_user:
    login_user: root
    db: postgres
    name: "{{ item.username }}"
    role_attr_flags: "{{ none if item.role_attributes|default(none) == none else item.role_attributes.values()|join(',') }}"
    password: "{{ item.password|default(none) }}"
  loop_control:
    label: "{{ item.username }}"
  with_items: "{{ postgresql.users.values()|list }}"

- name: Assign privs
  with_items: "{{ postgresql.privileges.values() | list }}"
  community.postgresql.postgresql_privs:
    objs: "{{ item.objs | default(omit) }}"
    schema: "{{ item.schema | default(omit) }}"
    database: "{{ item.database }}"
    state: present
    privs: "{{ item.privs | join(',') }}"
    type: "{{ item.type | default('table') }}"
    roles: "{{ item.username }}"
    grant_option: true
