---
- name: Converge
  hosts: all
  environment:
    GITHUB_ACTIONS: "maybe"
    ANSIBLE_HASH_BEHAVIOUR: merge
  tasks:
    - name: "Include ansible-proserver-postgresql"
      ansible.builtin.include_role:
        name: "ansible-proserver-postgresql"
